issuer: https://token.actions.githubusercontent.com

subject_pattern: repo:DataDog/build-plugins:.*

claim_pattern:
  event_name: workflow_dispatch
  job_workflow_ref: DataDog/build-plugins/.github/workflows/bump.yaml@.*

permissions:
  contents: write
  pull-requests: write
