issuer: https://token.actions.githubusercontent.com

subject_pattern: repo:DataDog/build-plugins:ref:refs/heads/master

claim_pattern:
  event_name: workflow_dispatch
  ref: refs/heads/master
  ref_protected: "true"
  job_workflow_ref: DataDog/build-plugins/.github/workflows/bump.yaml@.*

permissions:
  contents: write  # Required to create tags and push the bump commit
  pull_requests: write  # Required to create pull requests
