name: Publish packages on NPM
on:
  push


jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'

    - run: echo "Coucou"
