name: Continuous Integration

on: pull_request

jobs:
  unit-test:
    strategy:
      fail-fast: false
      matrix:
        node:
        - node-version-file: 'package.json'
        - node-version: 20.x

    name: Unit tests w/ Node.js ${{matrix.node}}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Node ${{matrix.node}}
      uses: actions/setup-node@v4
      with: ${{matrix.node}}
    - run: yarn install
    - run: yarn build:all
    - run: yarn test

  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
    - run: yarn install
    - run: yarn build:all
    - run: yarn typecheck:all
    - run: yarn cli integrity
    - run: git diff --exit-code && git diff --cached --exit-code || (echo "Please run 'yarn cli integrity' and commit the result." && exit 1)
